-intstyle "pa" -incremental -L "work" -L "secureip" -o "testeverything_tb.exe" --prj "H:/Xilinx/project_4/project_4_5/project_4_5.sim/sim_1/behav/testeverything_tb.prj" -top "work.testeverything_tb" 
